version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - api
    environment:
        - REACT_APP_API_URL=http://localhost:8000


  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
        - "8000:8000"
    env_file:
      - ./api/.env

volumes:
    api_data:
